## 12_ Champion Model Optimisation (XGBoost)
Explainable AI Credit Risk Decision Platform: Integrating Structured Borrower Data, NLP-Driven Text Intelligence, and Macroeconomic Indicators for Transparent Lending Decisions.

#### Reason:
Systematically fine-tunes the hyperparameters and structural parameters of your best-performing model to maximize predictive accuracy.

In [13]:
# IMPORTS & CONFIGURATION
# ________________________________________

from __future__ import annotations

import gc
import logging
import warnings
from pathlib import Path
from datetime import datetime

import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.sparse as sparse

from scipy.stats import randint, uniform

from xgboost import XGBClassifier


from sklearn.model_selection import (
    RandomizedSearchCV,
    TimeSeriesSplit)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    classification_report)

warnings.filterwarnings("ignore")

RANDOM_STATE = 42

np.random.seed(RANDOM_STATE)

PROJECT_NAME = "Explainable AI Credit Risk Decision Platform"

NOTEBOOK_NAME = "12_champion_model_optimisation"

PROJECT_ROOT = Path.cwd()

FEATURE_STORE_DIR = PROJECT_ROOT / "data" / "feature_store"

MODEL_DIR = PROJECT_ROOT / "models"

REPORT_DIR = PROJECT_ROOT / "reports"

METRIC_DIR = REPORT_DIR / "metrics"

MODEL_DIR.mkdir(parents=True, exist_ok=True)

METRIC_DIR.mkdir(parents=True, exist_ok=True)

print(PROJECT_NAME)
print("=" * 50)
print(f"Notebook : {NOTEBOOK_NAME}")
print(f"Execution: {datetime.now():%Y-%m-%d %H:%M}")

Explainable AI Credit Risk Decision Platform
==================================================
Notebook : 12_champion_model_optimisation
Execution: 2026-07-21 11:08

In [4]:
# REUSABLE HELPER FUNCTIONS
# _____________________________________________

# logger
# ________________________

def get_logger():

    logger = logging.getLogger("ChampionModel")

    if not logger.handlers:

        logger.setLevel(logging.INFO)

        handler = logging.StreamHandler()

        formatter = logging.Formatter(
            "%(asctime)s | %(levelname)s | %(message)s")

        handler.setFormatter(formatter)

        logger.addHandler(handler)

    return logger

logger = get_logger()

In [49]:
# Load matrix
#___________________

def load_sparse_matrix(filename):

    logger.info(f"Loading {filename}")

    matrix = sparse.load_npz(FEATURE_STORE_DIR / filename)

    logger.info("Loaded successfully.")

    return matrix
    
# Load Target
#_______________________

def load_target():

    y_train = np.load(FEATURE_STORE_DIR / "y_train.npy")

    y_test = np.load(FEATURE_STORE_DIR / "y_test.npy")

    return y_train, y_test
    
# Save model
# _______________________

def save_model(model, filename):

    path = MODEL_DIR / filename

    joblib.dump(model, path)

    logger.info(f"Saved: {filename}")

In [50]:
# Model Evaluation
# _____________________________________

def evaluate_model(model, X_test, y_test):

    prediction = model.predict(X_test)

    probability = model.predict_proba(X_test)[:, 1]

    return pd.DataFrame({

        "Accuracy":[accuracy_score(y_test, prediction)],

        "Precision":[precision_score(y_test, prediction)],

        "Recall":[recall_score(y_test, prediction)],

        "F1":[f1_score(y_test, prediction)],

        "ROC_AUC":[roc_auc_score(y_test, probability)]})

# Clear Memory
#_________________________________________

def clear_memory(*objects):

    for obj in objects:
        del obj

    gc.collect()

    logger.info("Memory cleared.")

### Load Champion Model Dataset
##### ___________________________________
##### This notebook loads only Matrix D,

##### because it was selected as the champion feature set.

In [51]:
# LOAD CHAMPION DATASET
# _________________________________________

logger.info("Loading Champion Dataset")

matrix_D_train = load_sparse_matrix("matrix_D_train.npz")

matrix_D_test = load_sparse_matrix("matrix_D_test.npz")

y_train, y_test = load_target()

print()

print("Training Shape :", matrix_D_train.shape)

print("Testing Shape  :", matrix_D_test.shape)

print("Target Train   :", y_train.shape)

print("Target Test    :", y_test.shape)

2026-07-21 14:54:57,808 | INFO | Loading Champion Dataset
2026-07-21 14:54:57,810 | INFO | Loading matrix_D_train.npz
2026-07-21 14:54:58,269 | INFO | Loaded successfully.
2026-07-21 14:54:58,284 | INFO | Loading matrix_D_test.npz
2026-07-21 14:54:58,343 | INFO | Loaded successfully.

Training Shape : (400000, 91)
Testing Shape  : (100000, 91)
Target Train   : (400000,)
Target Test    : (100000,)

In [52]:
# VALIDATION
# ____________________________

assert matrix_D_train.shape[0] == y_train.shape[0]

assert matrix_D_test.shape[0] == y_test.shape[0]

logger.info("Dataset validation passed.")

2026-07-21 14:55:04,513 | INFO | Dataset validation passed.

In [53]:
# DEFINE HYPERPARAMETER SEARCH SPACE
# ___________________________________________________________

print("Define Hyperparameter Search Space")

logger.info("Building XGBoost hyperparameter search space...")

param_grid = {

    "n_estimators": randint(100, 500),

    "learning_rate": uniform(0.01, 0.19),

    "max_depth": randint(3, 10),

    "min_child_weight": randint(1, 10),

    "subsample": uniform(0.6, 0.4),

    "colsample_bytree": uniform(0.6, 0.4),

    "gamma": uniform(0.0, 5.0),

    "reg_alpha": uniform(0.0, 2.0),

    "reg_lambda": uniform(0.5, 3.0)}

logger.info(f"Total Hyperparameters : {len(param_grid)}")

display(pd.DataFrame({"Hyperparameter": param_grid.keys(),
                      
    "Distribution": [str(v) for v in param_grid.values()]}))

2026-07-21 14:55:13,924 | INFO | Building XGBoost hyperparameter search space...
2026-07-21 14:55:13,935 | INFO | Total Hyperparameters : 9

Define Hyperparameter Search Space

     Hyperparameter                                       Distribution
0      n_estimators  <scipy.stats._distn_infrastructure.rv_discrete...
1     learning_rate  <scipy.stats._distn_infrastructure.rv_continuo...
2         max_depth  <scipy.stats._distn_infrastructure.rv_discrete...
3  min_child_weight  <scipy.stats._distn_infrastructure.rv_discrete...
4         subsample  <scipy.stats._distn_infrastructure.rv_continuo...
5  colsample_bytree  <scipy.stats._distn_infrastructure.rv_continuo...
6             gamma  <scipy.stats._distn_infrastructure.rv_continuo...
7         reg_alpha  <scipy.stats._distn_infrastructure.rv_continuo...
8        reg_lambda  <scipy.stats._distn_infrastructure.rv_continuo...

In [54]:
# TIME-BASED CROSS VALIDATION
# ________________________________________________

print("Time-Based Cross Validation")

logger.info("Creating TimeSeriesSplit...")

tscv = TimeSeriesSplit(n_splits=5)

logger.info(f"Number of folds : {tscv.get_n_splits()}")

print(tscv)

2026-07-21 14:55:21,327 | INFO | Creating TimeSeriesSplit...
2026-07-21 14:55:21,329 | INFO | Number of folds : 5

Time-Based Cross Validation
TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None)

In [55]:
# RANDOMIZED SEARCH
# _________________________________________________

print("Randomized Hyperparameter Optimisation")

negative = (y_train == 0).sum()

positive = (y_train == 1).sum()

scale_pos_weight = negative / positive

baseline_model = XGBClassifier(

    objective="binary:logistic",

    eval_metric="logloss",

    random_state=RANDOM_STATE,

    tree_method="hist",

    n_jobs=-1,

    scale_pos_weight=scale_pos_weight)

random_search = RandomizedSearchCV(

    estimator=baseline_model,

    param_distributions=param_grid,

    n_iter=30,

    scoring="roc_auc",

    cv=tscv,

    verbose=2,

    random_state=RANDOM_STATE,

    n_jobs=-1,

    refit=True)

logger.info("Starting optimisation...")

random_search.fit(

    matrix_D_train,

    y_train)

logger.info("Optimisation completed.")

2026-07-21 14:55:26,992 | INFO | Starting optimisation...

Randomized Hyperparameter Optimisation
Fitting 5 folds for each of 30 candidates, totalling 150 fits

2026-07-21 15:15:46,954 | INFO | Optimisation completed.

In [57]:
# BEST PARAMETERS
# ____________________________________________

best_params = random_search.best_params_

best_score = random_search.best_score_

print("\nBest ROC-AUC (CV):", round(best_score,4))

display(pd.DataFrame({

    "Parameter": best_params.keys(),

    "Best Value": best_params.values()}))

Best ROC-AUC (CV): 0.7216

          Parameter  Best Value
0  colsample_bytree    0.824511
1             gamma    3.854836
2     learning_rate    0.103821
3         max_depth    3.000000
4  min_child_weight    3.000000
5      n_estimators  162.000000
6         reg_alpha    1.791527
7        reg_lambda    1.926111
8         subsample    0.825310

In [59]:
# TRAIN OPTIMISED XGBOOST
# _____________________________________________

print("Train Optimised Champion Model")

best_model = random_search.best_estimator_

best_model.fit(matrix_D_train,y_train)

save_model(best_model,"champion_xgboost.pkl")

logger.info("Champion model trained and saved.")

Train Optimised Champion Model
[CV] END colsample_bytree=0.7334834444556088, gamma=0.7143340896097039, learning_rate=0.13366880986028204, max_depth=7, min_child_weight=2, n_estimators=443, reg_alpha=1.6648852816008435, reg_lambda=1.1370173320348285, subsample=0.6727299868828402; total time=  31.9s
[CV] END colsample_bytree=0.9895022075365837, gamma=1.1638567021515211, learning_rate=0.02721522256123595, max_depth=8, min_child_weight=3, n_estimators=463, reg_alpha=1.0284688768272232, reg_lambda=2.2772437065861273, subsample=0.6185801650879991; total time=  35.7s
[CV] END colsample_bytree=0.8430179407605753, gamma=0.8526206184364576, learning_rate=0.02235980266720311, max_depth=6, min_child_weight=9, n_estimators=415, reg_alpha=1.1265764356910786, reg_lambda=1.6562495076197483, subsample=0.6063865008880857; total time=  56.0s
[CV] END colsample_bytree=0.9314950036607718, gamma=1.7837666334679465, learning_rate=0.06337755684060234, max_depth=6, min_child_weight=9, n_estimators=256, reg_alpha=1.6043939615080793, reg_lambda=0.7236519310393125, subsample=0.9947547746402069; total time=  15.8s
[CV] END colsample_bytree=0.9705203514053395, gamma=3.2553851275097223, learning_rate=0.18384233835331837, max_depth=3, min_child_weight=8, n_estimators=367, reg_alpha=0.6617960497052984, reg_lambda=0.6906750508580709, subsample=0.7243929286862649; total time=   6.6s
[CV] END colsample_bytree=0.9705203514053395, gamma=3.2553851275097223, learning_rate=0.18384233835331837, max_depth=3, min_child_weight=8, n_estimators=367, reg_alpha=0.6617960497052984, reg_lambda=0.6906750508580709, subsample=0.7243929286862649; total time=13.4min
[CV] END colsample_bytree=0.8245108790277985, gamma=3.854835899772805, learning_rate=0.10382116330923424, max_depth=3, min_child_weight=3, n_estimators=162, reg_alpha=1.7915271913470387, reg_lambda=1.9261106695463353, subsample=0.8253102287905535; total time=   8.8s
[CV] END colsample_bytree=0.878206434570451, gamma=0.6966572720293784, learning_rate=0.12483930206278528, max_depth=9, min_child_weight=4, n_estimators=112, reg_alpha=0.15395981965758598, reg_lambda=1.369254358741304, subsample=0.6644885149016018; total time=   9.7s
[CV] END colsample_bytree=0.878206434570451, gamma=0.6966572720293784, learning_rate=0.12483930206278528, max_depth=9, min_child_weight=4, n_estimators=112, reg_alpha=0.15395981965758598, reg_lambda=1.369254358741304, subsample=0.6644885149016018; total time=  24.5s
[CV] END colsample_bytree=0.7425191352307899, gamma=4.53414220772877, learning_rate=0.06170512738308071, max_depth=5, min_child_weight=9, n_estimators=215, reg_alpha=0.705137712668338, reg_lambda=1.4143437744740872, subsample=0.6658623412571767; total time=  26.9s
[CV] END colsample_bytree=0.7454518409517176, gamma=4.858910413604804, learning_rate=0.19286498603900115, max_depth=8, min_child_weight=7, n_estimators=485, reg_alpha=1.424541179848884, reg_lambda=0.9442607898601997, subsample=0.9990961940195767; total time=  19.7s
[CV] END colsample_bytree=0.7957811041110252, gamma=4.928252270553004, learning_rate=0.05599050158718508, max_depth=6, min_child_weight=7, n_estimators=302, reg_alpha=0.7393089121228089, reg_lambda=1.2264798148322775, subsample=0.9212559025519583; total time=   5.7s
[CV] END colsample_bytree=0.7957811041110252, gamma=4.928252270553004, learning_rate=0.05599050158718508, max_depth=6, min_child_weight=7, n_estimators=302, reg_alpha=0.7393089121228089, reg_lambda=1.2264798148322775, subsample=0.9212559025519583; total time=  17.8s
[CV] END colsample_bytree=0.7881202537784153, gamma=4.917115704474215, learning_rate=0.08577664406446507, max_depth=9, min_child_weight=1, n_estimators=300, reg_alpha=0.6415601299434717, reg_lambda=1.0595555311995626, subsample=0.6163100566219055; total time=  32.6s
[CV] END colsample_bytree=0.7546941385202149, gamma=4.6836499436836725, learning_rate=0.03612897938773872, max_depth=6, min_child_weight=9, n_estimators=250, reg_alpha=1.0828959476551316, reg_lambda=2.5873531980352467, subsample=0.6914200087189198; total time=  21.2s
[CV] END colsample_bytree=0.8532405829093072, gamma=1.6951489552435035, learning_rate=0.07634981917640557, max_depth=5, min_child_weight=4, n_estimators=251, reg_alpha=0.8090162542443802, reg_lambda=3.163310296282879, subsample=0.9403713795070051; total time=  10.7s
[CV] END colsample_bytree=0.9742539976883791, gamma=3.926703255569718, learning_rate=0.13710776839570346, max_depth=8, min_child_weight=3, n_estimators=211, reg_alpha=0.2029430857320642, reg_lambda=2.4905053073241676, subsample=0.6020246335384875; total time=  19.3s
[CV] END colsample_bytree=0.6643232205669994, gamma=2.7436689468329307, learning_rate=0.14146008756161174, max_depth=7, min_child_weight=9, n_estimators=260, reg_alpha=0.036150727231041735, reg_lambda=1.9816811455503038, subsample=0.6715290836885315; total time=  34.9s
[CV] END colsample_bytree=0.7996773519539009, gamma=2.8600209960459155, learning_rate=0.15602526271819872, max_depth=3, min_child_weight=5, n_estimators=105, reg_alpha=0.7403174005108888, reg_lambda=0.5463698495866023, subsample=0.9713274250350902; total time=   1.9s
[CV] END colsample_bytree=0.7996773519539009, gamma=2.8600209960459155, learning_rate=0.15602526271819872, max_depth=3, min_child_weight=5, n_estimators=105, reg_alpha=0.7403174005108888, reg_lambda=0.5463698495866023, subsample=0.9713274250350902; total time=   5.4s
[CV] END colsample_bytree=0.749816047538945, gamma=4.75357153204958, learning_rate=0.14907884894416698, max_depth=7, min_child_weight=5, n_estimators=202, reg_alpha=0.8916655057071823, reg_lambda=0.7999247474540087, subsample=0.7836995567863468; total time=  30.0s
[CV] END colsample_bytree=0.9895022075365837, gamma=1.1638567021515211, learning_rate=0.02721522256123595, max_depth=8, min_child_weight=3, n_estimators=463, reg_alpha=1.0284688768272232, reg_lambda=2.2772437065861273, subsample=0.6185801650879991; total time=  21.2s
[CV] END colsample_bytree=0.8430179407605753, gamma=0.8526206184364576, learning_rate=0.02235980266720311, max_depth=6, min_child_weight=9, n_estimators=415, reg_alpha=1.1265764356910786, reg_lambda=1.6562495076197483, subsample=0.6063865008880857; total time=  22.7s
[CV] END colsample_bytree=0.6923575302488596, gamma=1.2051273301300585, learning_rate=0.13982006857683707, max_depth=6, min_child_weight=8, n_estimators=134, reg_alpha=1.8186408041575641, reg_lambda=1.2763399448000508, subsample=0.8650089137415928; total time=   3.9s
[CV] END colsample_bytree=0.6923575302488596, gamma=1.2051273301300585, learning_rate=0.13982006857683707, max_depth=6, min_child_weight=8, n_estimators=134, reg_alpha=1.8186408041575641, reg_lambda=1.2763399448000508, subsample=0.8650089137415928; total time=  10.6s
[CV] END colsample_bytree=0.7246844304357644, gamma=2.600340105889054, learning_rate=0.11387495307522313, max_depth=8, min_child_weight=2, n_estimators=317, reg_alpha=0.8995082667395313, reg_lambda=1.6854507080054433, subsample=0.9706635463175177; total time=   5.1s
[CV] END colsample_bytree=0.7246844304357644, gamma=2.600340105889054, learning_rate=0.11387495307522313, max_depth=8, min_child_weight=2, n_estimators=317, reg_alpha=0.8995082667395313, reg_lambda=1.6854507080054433, subsample=0.9706635463175177; total time=  15.2s
[CV] END colsample_bytree=0.8909087983425683, gamma=1.632703844029177, learning_rate=0.11838435513702589, max_depth=6, min_child_weight=9, n_estimators=289, reg_alpha=0.6506606615265287, reg_lambda=1.666031869068446, subsample=0.7085396127095583; total time=  22.1s
[CV] END colsample_bytree=0.908897907718663, gamma=0.993578407670862, learning_rate=0.011049202253484457, max_depth=5, min_child_weight=3, n_estimators=180, reg_alpha=1.4226839054973, reg_lambda=2.870526621593617, subsample=0.8423839899124046; total time=  15.7s
[CV] END colsample_bytree=0.9705203514053395, gamma=3.2553851275097223, learning_rate=0.18384233835331837, max_depth=3, min_child_weight=8, n_estimators=367, reg_alpha=0.6617960497052984, reg_lambda=0.6906750508580709, subsample=0.7243929286862649; total time=13.7min
[CV] END colsample_bytree=0.878206434570451, gamma=0.6966572720293784, learning_rate=0.12483930206278528, max_depth=9, min_child_weight=4, n_estimators=112, reg_alpha=0.15395981965758598, reg_lambda=1.369254358741304, subsample=0.6644885149016018; total time=  21.2s
[CV] END colsample_bytree=0.7425191352307899, gamma=4.53414220772877, learning_rate=0.06170512738308071, max_depth=5, min_child_weight=9, n_estimators=215, reg_alpha=0.705137712668338, reg_lambda=1.4143437744740872, subsample=0.6658623412571767; total time=  15.5s
[CV] END colsample_bytree=0.8136357677501768, gamma=2.424149856794916, learning_rate=0.1415628462491514, max_depth=4, min_child_weight=8, n_estimators=414, reg_alpha=0.6464058640415105, reg_lambda=2.056371865230098, subsample=0.881207583558071; total time=  29.4s
[CV] END colsample_bytree=0.706712405710114, gamma=4.883074779163264, learning_rate=0.08809703253046394, max_depth=9, min_child_weight=5, n_estimators=323, reg_alpha=1.8165317719333074, reg_lambda=1.2186856720009174, subsample=0.6579579488364892; total time=  33.1s
[CV] END colsample_bytree=0.7881202537784153, gamma=4.917115704474215, learning_rate=0.08577664406446507, max_depth=9, min_child_weight=1, n_estimators=300, reg_alpha=0.6415601299434717, reg_lambda=1.0595555311995626, subsample=0.6163100566219055; total time=  56.3s
[CV] END colsample_bytree=0.8532405829093072, gamma=1.6951489552435035, learning_rate=0.07634981917640557, max_depth=5, min_child_weight=4, n_estimators=251, reg_alpha=0.8090162542443802, reg_lambda=3.163310296282879, subsample=0.9403713795070051; total time=  17.8s
[CV] END colsample_bytree=0.6643232205669994, gamma=2.7436689468329307, learning_rate=0.14146008756161174, max_depth=7, min_child_weight=9, n_estimators=260, reg_alpha=0.036150727231041735, reg_lambda=1.9816811455503038, subsample=0.6715290836885315; total time=  17.3s
[CV] END colsample_bytree=0.7465875138331439, gamma=3.720852615282811, learning_rate=0.14697858560790458, max_depth=3, min_child_weight=3, n_estimators=474, reg_alpha=0.5009236372111683, reg_lambda=2.2696125426816316, subsample=0.9915571433100037; total time=  11.8s
[CV] END colsample_bytree=0.7465875138331439, gamma=3.720852615282811, learning_rate=0.14697858560790458, max_depth=3, min_child_weight=3, n_estimators=474, reg_alpha=0.5009236372111683, reg_lambda=2.2696125426816316, subsample=0.9915571433100037; total time=  21.8s

2026-07-21 15:20:28,429 | INFO | Saved: champion_xgboost.pkl
2026-07-21 15:20:28,430 | INFO | Champion model trained and saved.

In [64]:
# PERFORMANCE COMPARISON
# ________________________________________________

print("Performance Comparison")

optimised_results = evaluate_model(

    best_model,

    matrix_D_test,

    y_test)

optimised_results.insert(

    0,

    "Model",

    "Optimised XGBoost")

baseline_results = pd.read_csv(

    METRIC_DIR / "xgboost_results.csv")

baseline_results = (baseline_results[
    
    baseline_results["Dataset"]=="Matrix D"].copy())

baseline_results.insert(

    0,

    "Model",

    "Baseline XGBoost")

optimised_results.insert(
    1,
    
    "Dataset",
    
    "Matrix D")

comparison = pd.concat([baseline_results,
                        
                        optimised_results],
                       
                       ignore_index=True)

display(comparison)

Performance Comparison

,Model,Dataset,Accuracy,Precision,Recall,F1,ROC_AUC
0,Baseline XGBoost,Matrix D,0.63508,0.266932,0.704602,0.387183,0.724106
1,Optimised XGBoost,Matrix D,0.63182,0.266072,0.711081,0.387245,0.724671

In [65]:
# PERFORMANCE IMPROVEMENT
# ________________________________________

metrics = ["Accuracy", "Precision", "Recall", "F1", "ROC_AUC"]

improvement = pd.DataFrame({

    "Metric": metrics,

    "Baseline": baseline_results.iloc[0][metrics].values,

    "Optimised": optimised_results.iloc[0][metrics].values})

improvement["Difference"] = (

    improvement["Optimised"]

    -

    improvement["Baseline"])

display(improvement.round(4))

      Metric  Baseline Optimised Difference
0   Accuracy   0.63508   0.63182   -0.00326
1  Precision  0.266932  0.266072   -0.00086
2     Recall  0.704602  0.711081   0.006479
3         F1  0.387183  0.387245   0.000062
4    ROC_AUC  0.724106  0.724671   0.000565

In [70]:
# EXPORT MODEL EVALUATION ARTEFACTS
# ___________________________________________________

print("Export Model Evaluation Artefacts")

REPORT_DIR.mkdir(parents=True, exist_ok=True)

# Comparison Table

comparison.to_csv(REPORT_DIR / "model_comparison.csv",index=False)

# Best Model Only

champion_results = comparison.loc[comparison["Model"] == "Optimised XGBoost"]

champion_results.to_csv(REPORT_DIR / "champion_model_results.csv",index=False)

joblib.dump(best_model,MODEL_DIR / "optimised_xgboost.pkl")

# Performance Summary

summary = comparison.describe()

summary.to_csv(REPORT_DIR / "model_performance_summary.csv")

logger.info("Model evaluation artefacts exported successfully.")

2026-07-22 12:22:14,033 | INFO | Model evaluation artefacts exported successfully.

Export Model Evaluation Artefacts